app/shared/components/Logo/component.jsx, app/shared/components/Masthead/component.jsx, app/shared/fixtures/primary-navigation.js
A little diddy one - adding an alt tag in!
=> [RFR] Applying correct alt text for logo

app/client/index.jsx, app/server/api/v1/api.js, app/shared/routes.jsx, app/shared/utilities.js, config.yaml, contentful/contentModel/contentful-export-ip74mqmfgvqf-develop.json
Have created a single 'homepage' entry in contentful, pulling that in via it's entry id (in the config.yaml)
=> [RFR] adding homepage and general page loading

app/shared/components/Page/component.jsx, contentful/contentModel/contentful-export-ip74mqmfgvqf-develop.json
the code change is a measly couple of lines, the rest of the commit is an export of the contentful content model.
=> [RFR] Feature/ttf 64 schema tags

app/server/api/v1/api.js, app/shared/actions.js, app/shared/components/Page/component.jsx, app/shared/components/PageGeneral/component.jsx, app/shared/components/PageNews/component.jsx, app/shared/components/PageNotFound/component.jsx, app/shared/contentful.jsx, app/shared/newRoutes.jsx
not entirely sure this is the best way to allow for URLs set by contentful, but please review, comment, like and subscribe.
=> [RFR] news, general & 404 page fixes

app/shared/components/Page/component.jsx, app/shared/components/PageDrugAZ/component.jsx, app/shared/components/PageNotFound/component.jsx, app/shared/components/Panel/style.scss, app/shared/components/Toggle/component.jsx, app/shared/components/Toggle/style.scss, app/shared/components/Typography/style.scss
Couple more need doing but could you please take a look at these before Dan gets going on them @openbook @Koded ? Thank you : )
=> [WIP] Fix/10 23 fixes

.eslintrc, app/shared/components/Breakpoints/component.jsx, app/shared/components/Breakpoints/style.scss, app/shared/components/Masthead/component.jsx, app/shared/components/Nav/_style.scss, app/shared/components/Nav/component.jsx, grunt/pa11y.js, static/ui/scss/main.scss
Fixes for: https://digitaltools.phe.org.uk/projects/TTF/issues/TTF-625?filter=allopenissues
=> [RFR] Accessibility Navigation Fixes

.eslintrc, app/shared/components/Breakpoints/component.jsx, app/shared/components/Breakpoints/style.scss, app/shared/components/Masthead/component.jsx, app/shared/components/Nav/_style.scss, app/shared/components/Nav/component.jsx, grunt/pa11y.js, static/ui/scss/main.scss, static/ui/svg/logo-frank--alt.svg
=> [RFR] Change logo color

app/shared/components/Footer/style.scss, static/ui/scss/_custom.scss, static/ui/scss/_layout.scss
https://digitaltools.phe.org.uk/browse/TTF-524
=> [RFR] Fix: TTF-524 - footer at bottom

app/server/api/v1/api.js, app/server/api/v1/apisearch.js, app/shared/actions.js, app/shared/components/FormGroupAutocomplete/component.jsx, app/shared/components/PageNewsList/component.jsx, app/shared/components/PageSearch/component.jsx, app/shared/components/Pagination/component.jsx, app/shared/containers/PageNewsListContainer/component.jsx, app/shared/containers/PageSearchContainer/component.jsx, config.yaml, grunt/tasks/contentful.js
added pagination (for search and news list).  Ready to merge.
=> [WIP] Feature/ttf 357 search setup

app/shared/components/PageNewsList/component.jsx, app/shared/containers/PageNewsListContainer/component.jsx, app/shared/newRoutes.jsx
@openbook - if you get a chance could you add in some 404 magic for the pagination (or would you suggest resetting `/latest/6` to be just `/latest`if it exceeds the number of pages there are?)
=> [RFR] Feature/pagination bookmarking

app/shared/components/FormGroup/component.jsx, app/shared/components/FormGroup/style.scss, app/shared/components/PageContactForm/component.jsx, app/shared/components/Select/component.jsx, app/shared/components/Textarea/component.jsx, app/shared/newRoutes.jsx
This is technically an RFR but I need to do the start live chat page too (essentially exactly the same)
=> [WIP] Feature/ttf 760 form pages

app/shared/components/Divider/style.scss, app/shared/components/Footer/style.scss, app/shared/components/PageSupport/component.jsx, static/ui/scss/_utilities.scss
Updating in line with new page design / layout
=> [RFR] Feature/ttf 67 treatment centres

app/server/api/v1/api.js, app/shared/components/Article/component.jsx, app/shared/components/FormGroup/component.jsx, app/shared/components/LinkDrugName/component.jsx, app/shared/components/PageDrugAZ/component.jsx, app/shared/components/PageNews/component.jsx, app/shared/components/PageNewsList/component.jsx
Adding correct related drugs and tidying / refactoring and reusing other components
=> [RFR] Feature/news article

config.preview.yaml, config.staging.yaml, config.yaml
will need to update the contentful api keys on the servers once this is merged
=> [RFR] switching to master contentful branch

app/server/contentful/webhooks.js, app/shared/contentful.jsx, app/shared/elasticSearch.jsx
adding webhook to react to publish/unpublish actions on news, general content & drug page updates
=> [RFR] Updating CMS to ElasticSearch push

app/shared/components/FormGroup/style.scss, app/shared/components/FormGroupAutocomplete/component.jsx, app/shared/components/PageDrugAZ/component.jsx, app/shared/components/PageHome/component.jsx, app/shared/components/PageNews/component.jsx, package-lock.json
Been tinkering with the autosuggest
=> [RFR] accessibility fixes 20181119

app/server/index.jsx, app/shared/components/Button/style.scss, app/shared/components/CookieBar/component.jsx, app/shared/components/Masthead/component.jsx, app/shared/components/Typography/style.scss, package-lock.json, package.json, static/ui/svg/cross-red.svg
This is for the visual aspect of the bar - the react-cookies plugin is not working _quite_ as planned but perhaps we can add that in properly later?
=> [WIP] Feature/ttf 762 cookie bar

app/shared/components/Head/component.jsx, app/shared/components/PageGeneral/component.jsx, grunt/aliases.yaml, grunt/sass.js, package.json
=> [RFR] Perf optimisations

app/shared/contentful.jsx, contentful/migrations/v0.1.4-embedded-videos.js, package-lock.json, package.json
There's not many changes required to the app here, but, I've ....
- created a new 'video' content model in contentful via the migration file
- added a 'header video' field to the news content model (it's assumed that if a value is added to this field it will display a video once the header is clicked).  The video fields will be available in the pageNews component at `props.fields.headerVideo.fields.embedUrl`
- also updated the rich text 'factory' function to (temporarily) show the video url and title in a paragraph on the page (this url can be passed to any 'video' component setup later).
=> [RFR] adding migration for embed url fields & contentful rich text factory

app/shared/components/PageOffline/component.jsx
=> [RFR] removing email address

app/shared/components/PageHome/component.jsx, app/shared/containers/HomepageContainer/component.jsx, contentful/migrations/v0.1.4-homepage-warning.js
homepage warnings!
- 2 new CMS fields added to the homepage content model
- optionally show a message with/without a link to either a drug or news page.
🎉
=> [RFR] adding warning message field cms migration & container/component changes

app/shared/containers/HomepageContainer/component.jsx, config.uat.yaml
updating 'read more' text to 'watch now'
=> [RFR] Feature/ttf 350 embedded videos

app/shared/components/AlertSiteMessage/component.jsx, app/shared/components/AmpHead/component.jsx, app/shared/components/AmpPageNews/component.jsx, app/shared/components/AmpPicture/component.jsx, app/shared/components/AmpVideo/component.jsx, app/shared/components/MessageBar/component.jsx, app/shared/components/PageSupport/component.jsx, app/shared/containers/SiteMessageContainer/component.jsx, app/shared/contentful.jsx
rolled a few fixes in to this:
- TTF-1349 - added clientonly around the gmaps components so that the div isn't reloaded on mobile
- TTF-1345 - AMP page fix for article + adding videos
- TTF-1346 - Fix for AMP pictures
- TTF-1348 - Message bar fix - deduping the message bar on homepage
=> [RFR] Fixes/message bar map

app/shared/components/ArticleSupport/component.jsx
https://digitaltools.phe.org.uk/browse/TTF-1371
=> Fix: #TTF-1371 - Reinstate distance

app/shared/components/Accent/style.scss, app/shared/components/Article/component.jsx, app/shared/components/Card/component.jsx, app/shared/components/Form/style.scss, app/shared/components/FormGroupAutocomplete/component.jsx, app/shared/components/LinkDrugName/component.jsx, app/shared/components/PageDrugAZ/component.jsx, app/shared/components/Time/style.scss, static/ui/scss/main.scss
This PR addresses the following sprint tasks
- Normalising A-Z page drug styles (removing descriptions)
- Hiding the post date from articles
- Adding a search box to the A-Z page
=> Sprint tasks

app/shared/components/AccessibleSearch/component.jsx, app/shared/components/Button/component.jsx, app/shared/components/Form/component.jsx, app/shared/components/GoogleAnalytics/component.jsx, package-lock.json, package.json
Adds analytics v4 and allows fuzzy search via pressing the search button
=> ga v4 and search improvements
